version: '3.8'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
  
  database:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  
volumes:
  postgres_data: