# Generated by Django 4.0.5 on 2022-06-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('departed', 'departed'), ('arrived', 'arrived'), ('cancelled', 'cancelled')], default='pending', max_length=10),
        ),
    ]
